### ISSUE TITLE
Support for FP8

### ISSUE THREAD

**Issue by LuLmaster69** [laksjdjf/cgem156-ComfyUI#2]
Could you please add support for FP8 mode in ComfyUI?

**Comment by LuLmaster69** [comment]
Currently it says 

> Error occurred when executing AttentionCouple|cgem156:
> 
> "sum_cuda" not implemented for 'Float8_e4m3fn'

**Comment by laksjdjf** [comment]
maybe fixed

**Comment by LuLmaster69** [comment]
yes it works, thanks.
