### ISSUE TITLE
donation?

### ISSUE THREAD

**Issue by cubiq** [laksjdjf/cgem156-ComfyUI#3]
Hey @laksjdjf do you have a paypal account? I'd like to send you something for all your hard work, especially the initial code for the IPAdapter. Please contact me if you want, you find my contact info in my profile too

**Comment by laksjdjf** [comment]
I work on the basis of my personal interests.
Interest in IP adapters has waned because of a lack of interest in face swapping, not because of money.

**Comment by laksjdjf** [comment]
I'm not going to accept donate, but I'll give you my Twitter account so you can contact me if you need anything.
My acount is furusu@gcem156.
