### ISSUE TITLE
Load LoRA Weight OnlyノードでSDXLのlbwを指定するとエラー

### ISSUE THREAD

**Issue by hybs3288** [laksjdjf/cgem156-ComfyUI#6]
Load LoRA Weight OnlyノードでSDXLのlbwを指定するとエラーが発生します。

<img width="479" alt="cap" src="https://github.com/laksjdjf/cgem156-ComfyUI/assets/95919541/f0df074f-2cbf-4ed4-940a-5e46e4f2814c">
<br><br>

```
LBW17TO26 = [2, 5, 8, 11, 12, 13, 15, 16, 17]
LBW12TO20 = [2, 3, 4, 5, 8, 18, 19, 20]
```

SDXLのlbwから通常のlbwへのblock変換用配列のindexが1ずつずれていると思います。

```
LBW17TO26 = [1, 4, 7, 10, 11, 12, 14, 15, 16]
LBW12TO20 = [1, 2, 3, 4, 7, 17, 18, 19]
```

**Comment by laksjdjf** [comment]
ありがとうございます！
多分その通りだと思うので、多分修正しました。
